version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "S3cr3T"
      POSTGRES_DB: "api"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - '/srv/postgres/postgres-data:/var/lib/postgres/data'

  api:
    build: ./app
    image: ghcr.io/just-another-muensterhack/api:main
    restart: always
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "S3cr3T"
      POSTGRES_NAME: "api"
      POSTGRES_DB: "api"
    depends_on:
      - postgres
    ports:
      - "8080:8000"
