version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    env_file: .postgres.env
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - '/srv/postgres/postgres-data:/var/lib/postgres/data'

  api:
    build: ./app
    image: ghcr.io/just-another-muensterhack/api:main
    container_name: helpwave-backend
    hostname: helpwave-backend
    restart: always
    env_file: .api.env
    depends_on:
      - postgres
    ports:
      - "8080:8000"
    networks:
      helpwave:
        ipv4_address: 172.0.0.3
